OS=Windows 11
Python.Version=3.11.9

Pytest.Version=9.0.3
Requests.Version=2.33.1
Allure-Pytest.Version=2.16.0
JSONSchema.Version=4.23.0
RerunFailures.Version=16.1

API.BaseURL=https://ark.cn-beijing.volces.com/api/v3
Test.Model=ep-20260527211839-psk77
Test.Model.Name=Doubao-Seed-2.0-pro

Test.Date=2026-05-26
Test.Author=liang
Test.TotalCases=36