[pytest]
addopts = -v -x --reruns 2 --reruns-delay 1 --alluredir=./reports
testpaths = ./test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: 冒烟测试，只运行核心功能用例